default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: bigdaddy_dev

test:
  <<: *default
  database: bigdaddy_test

production:
  <<: *default
  database: bigdaddy_prd